#
# Spring Config
#

spring:
  application:
    name: gateway-service
    
server:
  port: 8001


#
#   Eureka Config
#


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

